---
title: "Untitled"
author: "Court Campany"
date: "16 November 2016"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. 

## Interactive Plot

```{r massfractions}
library(plotrix)
tree_C <- read.csv("calculated_mass/chamber_carbon.csv")

  tree_C$standingtreemass <- with(tree_C, treeC-littercarbon)
  ##calculated component fractions
  tree_C$lmf <- with(tree_C, leafcarbon/standingtreemass)
  tree_C$smf <- with(tree_C, (boleC+branchC)/standingtreemass)
  tree_C$rmf <- with(tree_C, (rootC)/standingtreemass)
  ##order by treatment
  tree_C$treatment <- with(tree_C, paste(CO2_treatment, Water_treatment, sep="-"))  
  tree_C <- tree_C[order(tree_C$treatment),]

#simple mode for abline and sig
lmfmod <- lm(lmf ~ standingtreemass, data = tree_C)
smfmod <- lm(smf~ standingtreemass, data = tree_C)
rmfmod <- lm(rmf ~ standingtreemass, data = tree_C)

modresults <- data.frame(lmf = c(coef(lmfmod[1]), coef(lmfmod[2])), smf = c(coef(smfmod[1]), coef(smfmod[2])), rmf = c(coef(rmfmod[1]), coef(rmfmod[2])))

# plot bits ---------------------------------------------------------------

palette(c("blue", "red"))

leglab2 = c(expression(paste(aCO[2], ", " ,"wet")), expression(paste(aCO[2], ", " ,"dry")),
            expression(paste(eCO[2], ", " ,"wet")), expression(paste(eCO[2], ", " ,"dry")))

fraclab <- expression(Component~Mass~Fraction~~(g~g^-1))

# plotting ----------------------------------------------------------------

shinyApp(
  
ui = fluidPage(
      titlePanel(""),
      sidebarLayout(position="right",
        ##type selection
        sidebarPanel(
        style = "border-color: #cc2904; background-color: white; border-style:dotted;border-width:thick",
        radioButtons("whichcomponent", "Pick a component:",c("LMF" = "lmf", "SMF" = "smf", "RMF" =                              "rmf"))
        ),
  
      mainPanel(
        plotOutput('plot1'))
  )
  ),
  
server = function(input, output, session) {

    
    component_ss <- reactive({
      tree_C[, c("standingtreemass",input$whichcomponent,"Water_treatment","CO2_treatment")]
    })
    
    mod_ss <- reactive({
      modresults[,input$whichcomponent]
    })
    
output$plot1 <- renderPlot({

par(mar=c(5,6,1,1),las=1, cex.axis=1, cex.lab=1.25, mgp=c(3,1,0))
  
plot(tree_C$smf~tree_C$standingtreemass, ylim=c(0, .75), xlim=c(5000,21000), 
     xlab="Tree Biomass (g C)", ylab=fraclab, type='n') 

points(component_ss()[[2]] ~ component_ss()[[1]], cex=2, pch=c(1,19)[component_ss()[,3]], 
        col=c(rep("blue",6), rep("red", 6)))
        #col=component_ss()[,4])  #this doesnt work because of multiple column selection with input

ablineclip(mod_ss(), x1=min(component_ss()[[1]]), x2=max(component_ss()[[1]]),lwd=2) 
legend("topleft", leglab2, pch=c(19,1, 19, 1), col=c("blue", "blue", "red", "red"), bty='n')  
        
#if checkboxGroup use this input with looping to keep all (do not need reactives)
# for(variable in input$whichcomponent)points(tree_C[,"standingtreemass"], tree_C[,variable], col=tree_C[,"CO2_treatment"], cex=2, pch=c(1,19)[tree_C$Water_treatment])
# 
# for(variable in input$whichcomponent)ablineclip(modresults[,variable] , x1=min(tree_C$standingtreemass), x2=max(tree_C$standingtreemass),lwd=2)

  })
  }
)
```

## Bullets

- Bullet 1
- Bullet 2
- Bullet 3


